homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'

urlpatterns = [
    path('', views.index, name="index"),
    path('education/', views.education, name="education"),
    path('experience/', views.experience, name="experience"),
    path('project/', views.project, name="project"),
    path('schedule/create/', views.schedule_create_view, name="create"),
    path('schedule/', views.view_skejul, name = "view"),
    path('reset', views.reset, name = "reset"),
    path('delete/<pk>', views.delete, name = "delete")
]

story4daril/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from datetime import datetime, date
from django import forms
from django.utils import timezone

# Create your models here.

class Schedule(models.Model):
    activity        = models.CharField(max_length=120)
    place           = models.CharField(max_length=120)
    dateTime        = models.DateTimeField(default=timezone.now)
    category        = models.CharField(max_length=120)

homepage/forms.py
from django import forms

from .models import Schedule

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = [
            'activity',
            'place',
            'dateTime',
            'category'
        ]

homepage/views.py
from django.shortcuts import render, redirect

from .forms import ScheduleForm

from .models import Schedule

# Create your views here.
def index(request):
    return render(request, 'index.html')

def education(request):
    return render(request, 'education.html')

def experience(request):
    return render(request, 'experience.html')

def project(request):
    return render(request, 'project.html')

def schedule_create_view(request):
    form = ScheduleForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = ScheduleForm()
    context = {
        'form': form
    }

    return render(request, "schedule/schedule_create.html", context)

def view_skejul(request):
    skejuls = Schedule.objects.all()
    return render(request, 'schedule/schedule_view.html', {
        'skejuls': skejuls
    })

def reset(request):
    schedule = Schedule.objects.all()
    schedule.delete()
    return redirect('homepage:view')

def delete(request, pk):
    print(pk)
    schedule = Schedule.objects.get(pk=pk)
    schedule.delete()
    return redirect('homepage:view')

homepage/templates/education.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Daril Nofriansyah's Education</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container-fluid parallax1">
        </div>
        <div class="container-fluid education1">
            <div class="text-center row">
                <div class="col-sm-0 col-md-1 col-lg-1">
                    <a class="arrow_back" href="{% url 'homepage:index' %}"><img src="{% static 'images/Arrow-Free-Download-PNG.png' %}" width="60"></a>
                </div>
                <div class="col-sm-4 col-md-3 col-lg-3 sekolah">
                    <img class="img-fluid mw-100 h-auto logo_makara" src="{% static 'images/LOGO/makara-ui-fasilkom.png' %}" width="200">
                    <p class="text-center judul">Universitas<br>Indonesia</p>
                    <p class="text-center info">Bachelor of <strong>Computer Science</strong> <br> Majoring in <strong>Information System</strong></p>
                    <p class="text-center time">2018 - Present</p>
                </div>
                <div class="col-sm-4 col-md-3 col-lg-3 sekolah">
                    <img class="img-fluid mw-100 h-auto logo_labschool" src="{% static 'images/LOGO/Logo_Labschool.png' %}" width="195">
                    <p class="text-center judul">Labschool<br>Kebayoran</p>
                    <p class="text-center info">Class of <strong>2018</strong></p>
                </div>
                <div class="col-sm-0 col-md-1 col-lg-1">
                </div>
                <div class="text-right col-sm-4 col-md-4 col-lg-4 portrait">
                    <img src="{% static 'images/picture_education.jpg'%}" width="428">
                </div>
            </div>
        </div>
    </body>
</html>

homepage/templates/experience.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Daril Nofriansyah's Experience</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container-fluid parallax2">
        </div>
        <div class="container-fluid experience1">
            <div class="text-center row">
                <div class="text-left col-sm-8 col-md-5 col-lg-5 picture_experience">
                    <img class="img_experience" src="{% static 'images/picture_experience.jpg' %}" width="396">
                </div>
                <div class="text-center col-sm-4 col-md-7 col-lg-7">
                    <div class="text-center row atas">
                        <div class="col-md-4 grab">
                            <img class="grab_logo" src="{% static 'images/LOGO/1200px-Grab_(application)_logo.svg.png' %}" width="155">
                            <p class="text-center grab_tulisan"><strong>Records Management</strong> Internship</p>
                            <p class="text-center grab_tanggal">July 2019 - August 2019</p>
                        </div>
                        <div class="col-md-2"></div>
                        <div class="col-md-4 compfest">
                            <img class="compfest_logo" src="{% static 'images/LOGO/CompFest7-Logo-Black.png.4eb6e2f6e4ce0376cfd178b9437269f8.png' %}" width="250">
                            <p class="text-center compfest_tulisan">Staff of <strong>Seminar</strong> <br> In Charge of <strong>AR/VR Seminar</strong></p>
                            <p class="text-center compfest_tanggal">February 2019 - Present</p>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                    <div class="text-center row bawah">
                        <div class="col-md-2"></div>
                        <div class="col-md-6 bem">
                            <img class="bem_logo" src="{% static 'images/LOGO/horizontal-set@2x.png' %}" width="255">
                            <p class="text-center bem_tulisan">Staff of <strong>Sports Department</strong> <br> In Charge of <strong>Apresiasi Kontingen</strong></p>
                            <p class="text-center bem_tanggal">February 2019 - Present</p>
                        </div>
                        <div class="col-md-2 panah_exp">
                            <a class="arrow_back" href="{% url 'homepage:index' %}"><img src="{% static 'images/Arrow-Free-Download-PNG.png' %}" width="60"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

homepage/templates/index.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Daril Nofriansyah</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>
    <body>
        {% include 'nav.html' %}
        <div class="container-fluid home">
            <div class="row">
                <div class="col-sm-4 col-md-6 col-lg-6">
                </div>
                <div class="col-sm-8 col-md-6 col-lg-6 greetings">
                <p class="greetings_isi"> Hello! <br> I'm Daril Nofriansyah</p>
                <p class="text-justify deskripsi_isi">
                    An <strong>Undergraduate IT student</strong> who likes to solve problem. I am interested in obtaining new knowledge and skills, which I use to self-improve.
                </p>
                </div>
            </div>
        </div>
        <div class="container-fluid about" id="about">
            <div class="row">
                <div class="col-1"></div>
                <div class="col-4 education">
                    <div class="text-center container click_me_container">
                        <a class="text-center click_me" href="{% url 'homepage:education' %}">CLICK ME</a>
                    </div>
                </div>
                <div class="col-2"></div>
                <div class="col-4 experience">
                    <div class="text-center container click_me_container">
                        <a class="text-center click_me" href="{% url 'homepage:experience' %}">CLICK ME</a>
                    </div>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
        <div class="container-fluid contact" id="contact">
            <div class="containter-fluid contactMe">
                <p class="text-center tulisan_contact">Contact Me!</p>
            </div>
            <div class="container logo">
                <div class="text-center row">
                    <div class="col-sm-3 col-md-3 col-lg-3 logo">
                            <a class="logo1_gambar" href="#"><img src="{% static 'images/LOGO/281769.png' %}" width="100"></a>
                    </div>
                        <div class="col-sm-3 col-md-3 col-lg-3 logo">
                            <a class="logo2_gambar" href="https://www.instagram.com/darilnofriansyah/"><img src="{% static 'images/LOGO/4f0149647a160a47217615866f5469c4.png' %}" width="100"></a>
                    </div>
                    <div class="col-sm-3 col-md-3 col-lg-3 logo">
                        <a class="logo3_gambar" href="https://www.linkedin.com/in/daril-nofriansyah-153557147">
                            <img src="{% static 'images/LOGO/LinkedIn_logo_initials.png' %}" width="100">
                        </a>
                    </div>
                    <div class="col-sm-3 col-md-3 col-lg-3 logo">
                        <a class="logo4_gambar" href="https://line.me/R/"><img src="{% static 'images/LOGO/line-messenger.png' %}" width="100"></a>
                    </div>
                
                </div>
            </div>
        </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/nav.html
{% load static %}
<nav class="navbar sticky-top navbar-expand-lg navbar-light">
    <a class="navbar-brand" href=""><img src="{% static 'images/logo.png' %}" widht="60" height="60"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link active" href="{% url 'homepage:index' %}">HOME <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'homepage:view' %}">SCHEDULE</a>
            <a class="nav-item nav-link" href="{% url 'homepage:project' %}">GALLERY</a>
        </div>
    </div>
</nav>

homepage/templates/project.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Daril Nofriansyah's S&P</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container-fluid parallax3">
        </div>
        <div class="container-fluid quotes">
            <p class="text-center tulisan">
                Photography takes an instant out of time, <br>
                altering life by holding it still. <br>
            </p>
            <p class="text-center nama">
                -Dorothea Lange
            </p>
        </div>
        <div class="container-fluid under_construction">
            <p class="text-center under_tulisan">
                Page is Under Construction. <br>
                Back to <a class="balik" href="{% url 'homepage:index' %}">Home</a>
            </p>
        </div>
    </body>
</html>

homepage/templates/schedule/schedule_create.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Create Schedule</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>
    <body>
    {% include 'nav.html' %}
    <div class="text-center container-fluid form_hehe">
        <form method='POST' action="{% url 'homepage:create' %}"> {% csrf_token %}
        {{ form.as_p }}
        <input type = 'submit' value='Save' />
        <button><a href="{% url 'homepage:view' %}">Back</a></button>
        </form>
    </div>
    </body>

</html>

homepage/templates/schedule/schedule_view.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Create Schedule</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>

    <body>
        {% include 'nav.html' %}
        <h1>Schedule</h1>
        
        <table class="table">
            <thead>
                <th> Activity Name </th>
                <th> Date </th>
                <th> Place </th>
                <th> Category </th>
                <th> <th>
            </thead>
            <tbody>
                {% for skejul in skejuls %}
                <tr>
                <td>{{ skejul.activity }}</td>
                <td>{{ skejul.dateTime }}</td>
                <td>{{ skejul.place }}</td>
                <td>{{ skejul.category }}</td>
                <td><a href="{% url 'homepage:delete' pk=skejul.id %}"><button type ="button" class="btn btn-danger btn-sm">Delete</button><td>
                <tr>
                {% endfor %}
            </tbody>
        </table>

        <button><a href="{% url 'homepage:reset' %}" class="btn btn-danger btn-sm">Reset</a></button>
        <button><a href="{% url 'homepage:create' %}" class="btn btn-success btn-sm">Add</a></button>
        <div class="col-md-2 panah_schedule">
            <a class="arrow_back" href="{% url 'homepage:index' %}"><img src="{% static 'images/Arrow-Free-Download-PNG.png' %}" width="60"></a>
        </div>

    </body>


</html>